/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author clebe
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMNCadastro = new javax.swing.JMenu();
        jMNItmCliente = new javax.swing.JMenuItem();
        jMNItmOrdemServico = new javax.swing.JMenuItem();
        jMNItmUsuario = new javax.swing.JMenuItem();
        jMNRelatório = new javax.swing.JMenu();
        jMNRelClientes = new javax.swing.JMenuItem();
        jMNRelServicos = new javax.swing.JMenuItem();
        jMNSobre = new javax.swing.JMenu();
        jMNSair = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestão de Ordem de Serviço");
        setPreferredSize(new java.awt.Dimension(921, 552));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jMNCadastro.setMnemonic('C');
        jMNCadastro.setText("Cadastro");

        jMNItmCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMNItmCliente.setText("Cliente");
        jMNItmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMNItmClienteActionPerformed(evt);
            }
        });
        jMNCadastro.add(jMNItmCliente);

        jMNItmOrdemServico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMNItmOrdemServico.setText("Ordem Serviço");
        jMNCadastro.add(jMNItmOrdemServico);

        jMNItmUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMNItmUsuario.setText("Usuário");
        jMNItmUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMNItmUsuarioMouseClicked(evt);
            }
        });
        jMNItmUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMNItmUsuarioActionPerformed(evt);
            }
        });
        jMNCadastro.add(jMNItmUsuario);

        jMenuBar1.add(jMNCadastro);

        jMNRelatório.setMnemonic('R');
        jMNRelatório.setText("Relatório");

        jMNRelClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMNRelClientes.setText("Clientes");
        jMNRelatório.add(jMNRelClientes);

        jMNRelServicos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMNRelServicos.setText("Serviços");
        jMNRelServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMNRelServicosActionPerformed(evt);
            }
        });
        jMNRelatório.add(jMNRelServicos);

        jMenuBar1.add(jMNRelatório);

        jMNSobre.setMnemonic('S');
        jMNSobre.setText("Sobre");
        jMNSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMNSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMNSobre);

        jMNSair.setMnemonic('I');
        jMNSair.setText("Sair");
        jMNSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMNSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMNSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMNItmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMNItmClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMNItmClienteActionPerformed

    private void jMNItmUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMNItmUsuarioActionPerformed
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
    }//GEN-LAST:event_jMNItmUsuarioActionPerformed

    private void jMNRelServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMNRelServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMNRelServicosActionPerformed

    private void jMNSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMNSairMouseClicked
        int resposta = 0;
        JOptionPane.showConfirmDialog(null, "Deseja realmente sair do sistema?", "Atenção",JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION){
                System.exit(0);
            }       
    }//GEN-LAST:event_jMNSairMouseClicked

    private void jMNSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMNSobreMouseClicked
     
    }//GEN-LAST:event_jMNSobreMouseClicked

    private void jMNItmUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMNItmUsuarioMouseClicked
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
    }//GEN-LAST:event_jMNItmUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMNCadastro;
    private javax.swing.JMenuItem jMNItmCliente;
    private javax.swing.JMenuItem jMNItmOrdemServico;
    private javax.swing.JMenuItem jMNItmUsuario;
    private javax.swing.JMenuItem jMNRelClientes;
    private javax.swing.JMenuItem jMNRelServicos;
    private javax.swing.JMenu jMNRelatório;
    private javax.swing.JMenu jMNSair;
    private javax.swing.JMenu jMNSobre;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
