/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.UsuarioDAO;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author GERAL
 */
public class TelaUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaUsuario
     */
    public TelaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtlabel1 = new javax.swing.JLabel();
        jTxtlabel2 = new javax.swing.JLabel();
        jTxtlabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTxtlabel4 = new javax.swing.JLabel();
        jTextFieldFone = new javax.swing.JTextField();
        jTxtlabel5 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jTxtlabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTxtlabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBoxSenha = new javax.swing.JCheckBox();
        jButtonCreate = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jTextFieldUsuId = new javax.swing.JTextField();
        jButtonIdUser = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 153, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(640, 480));

        jTxtlabel1.setText("  *Id");

        jTxtlabel2.setText("*Campos Obrigatórios");

        jTxtlabel3.setText("*Nome");

        jTextFieldNome.setBackground(new java.awt.Color(204, 204, 255));

        jTxtlabel4.setText("Fone");

        jTextFieldFone.setBackground(new java.awt.Color(204, 204, 255));

        jTxtlabel5.setText("*Login");

        jTextFieldLogin.setBackground(new java.awt.Color(204, 204, 255));

        jTxtlabel6.setText("*Senha");

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 255));

        jTxtlabel7.setText("*Perfil");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "user" }));

        jCheckBoxSenha.setText("Alterar a senha");

        jButtonCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/create.png"))); // NOI18N
        jButtonCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCreateMouseClicked(evt);
            }
        });
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });

        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/update.png"))); // NOI18N
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete.png"))); // NOI18N
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jTextFieldUsuId.setBackground(new java.awt.Color(204, 204, 255));

        jButtonIdUser.setText("Pesquisar");
        jButtonIdUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIdUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtlabel6)
                    .addComponent(jTxtlabel4)
                    .addComponent(jTxtlabel3)
                    .addComponent(jTxtlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCheckBoxSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtlabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jButtonCreate)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonUpdate)
                                .addGap(31, 31, 31)
                                .addComponent(jButtonDelete)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextFieldFone, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtlabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLogin))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextFieldUsuId, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonIdUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                                .addComponent(jTxtlabel2))
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtlabel1)
                    .addComponent(jTxtlabel2)
                    .addComponent(jTextFieldUsuId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIdUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtlabel3)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtlabel4)
                    .addComponent(jTextFieldFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtlabel5)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtlabel6)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtlabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxSenha)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonCreate)
                    .addComponent(jButtonDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        Usuario obj = new Usuario();
        obj.setIdUser(Integer.parseInt(jTextFieldUsuId.getText()));
        obj.setUsuario(jTextFieldNome.getText());
        obj.setFone (jTextFieldFone.getText());
        obj.setLogin(jTextFieldLogin.getText());
        obj.setSenha(jPasswordField1.getText());
        obj.setPerfil(jComboBox1.getSelectedItem().toString());
        if ((jButtonIdUser.getText().isEmpty()) || (jTextFieldNome.getText().isEmpty()) || (jTextFieldLogin.getText().isEmpty()) || (jPasswordField1.getPassword().length == 0) || (jComboBox1.getSelectedItem().equals(" "))){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios");
        } else{
            UsuarioDAO dao = new UsuarioDAO();
            dao.adicionarUsuario(obj);
        }
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jButtonIdUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIdUserActionPerformed
        if (jButtonIdUser.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "}informe o id do usuário");
            jButtonIdUser.requestFocus();
        } else{
            UsuarioDAO dao = new UsuarioDAO();
            Usuario usuario = new Usuario();
            usuario = dao.buscarUsuario(Integer.parseInt(jTextFieldUsuId.getText()));
            jTextFieldNome.setText(usuario.getUsuario());
            jTextFieldLogin.setText(usuario.getLogin());
            jPasswordField1.setText(usuario.getSenha());
            jTextFieldFone.setText(usuario.getFone());
            jComboBox1.setSelectedItem(usuario.getPerfil());
            jButtonCreate.setEnabled(true);
            jButtonUpdate.setEnabled(false);
            jButtonDelete.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonIdUserActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        Usuario obj = new Usuario();
        obj.setIdUser(Integer.parseInt(jTextFieldUsuId.getText()));
        obj.setUsuario(jTextFieldNome.getText());
        obj.setFone (jTextFieldFone.getText());
        obj.setLogin(jTextFieldLogin.getText());
        obj.setSenha(jPasswordField1.getText());
        obj.setPerfil(jComboBox1.getSelectedItem().toString());
        if ((jButtonIdUser.getText().isEmpty()) || (jTextFieldNome.getText().isEmpty()) || (jTextFieldLogin.getText().isEmpty()) || (jPasswordField1.getPassword().length == 0) || (jComboBox1.getSelectedItem().equals(" "))){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios");
        } else{
            UsuarioDAO dao = new UsuarioDAO();
            dao.alterarUsuario(obj);
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCreateMouseClicked

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        Usuario obj = new Usuario();

        obj.setUsuario(jTextFieldNome.getText());
        obj.setFone(jTextFieldFone.getText());
        obj.setLogin(jTextFieldLogin.getText());
        obj.setSenha(jPasswordField1.getText());
       
        if((jTextFieldUsuId.getText()).isEmpty() || (jTextFieldNome.getText().isEmpty()) || (jTextFieldFone.getText().isEmpty()) || (jTextFieldLogin.getText().isEmpty()) || (jPasswordField1.getText().isEmpty())){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!!");
        } else{
            UsuarioDAO dao = new UsuarioDAO();
            dao.deletarUsuario(WIDTH);
           
            jTextFieldUsuId.setText(null);
            jTextFieldNome.setText(null);
            jTextFieldLogin.setText(null);
            jTextFieldFone.setText(null);
            jPasswordField1.setText(null);
           
            jButtonCreate.setEnabled(true);
            jButtonUpdate.setEnabled(false);
            jButtonDelete.setEnabled(false);
       
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonIdUser;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JCheckBox jCheckBoxSenha;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldFone;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldUsuId;
    private javax.swing.JLabel jTxtlabel1;
    private javax.swing.JLabel jTxtlabel2;
    private javax.swing.JLabel jTxtlabel3;
    private javax.swing.JLabel jTxtlabel4;
    private javax.swing.JLabel jTxtlabel5;
    private javax.swing.JLabel jTxtlabel6;
    private javax.swing.JLabel jTxtlabel7;
    // End of variables declaration//GEN-END:variables
}
